version: '3.5'

services:
  pictures:
    image: "salamantos/fancy_weather:pictures-1.0.0"
    build:
      context: .
      dockerfile: ./pictures/Dockerfile
    environment:
      - PICTURES_PORT=30600
    restart: on-failure
    ports:
      - 30600:30600
    networks:
      - fancy_weather
  poems:
    build:
      context: .
      dockerfile: ./poems/Dockerfile
    environment:
      - POEMS_PORT=30601
      - SQLALCHEMY_DATABASE_URI=sqlite:///poems_db.sqlite
      - FLASK_APP=poems
    restart: on-failure
    ports:
      - 30601:30601
    networks:
      - fancy_weather

# todo: replace with your service's configuration
#  some_core_service:
#    image: "salamantos/fancy_weather/pictures:1.0.0"
#    build:
#      context: .
#      dockerfile: ./pictures/Dockerfile
#    environment:
#      LOG_LEVEL: INFO
#        depends_on:
#          - pictures
#    networks:
#      - fancy_weather

networks:
  fancy_weather:
    driver: bridge
