version: '3.5'

services:
  pictures:
    image: "salamantos/fancy_weather:pictures-1.0.0"
    build:
      context: .
      dockerfile: ./pictures/Dockerfile
    environment:
      - PICTURES_PORT=30600
      - IMGUR_CLIENT=13bfb3e95351a14
    restart: on-failure
    ports:
      - 30600:30600
    networks:
      - fancy_weather
  poems:
    build:
      context: .
      dockerfile: ./poems/Dockerfile
    environment:
      - POEMS_PORT=30601
      - SQLALCHEMY_DATABASE_URI=sqlite:////usr/db/poems_db.sqlite
      - FLASK_APP=poems
    restart: on-failure
    ports:
      - 30601:30601
    networks:
      - fancy_weather
    volumes:
      - ./db/poems:/usr/db
  core:
    build:
      context: .
      dockerfile: ./core/Dockerfile
    environment:
      - TZ=Europe/Moscow
      - YANDEX_WEATHER_API_KEY
    restart: on-failure
    ports:
      - 5000:5000
    networks:
      - fancy_weather
    volumes:
      - ./db/core:/usr/db
  tg_bot:
    build:
      context: .
      dockerfile: ./tg_bot/Dockerfile
    environment:
      - TG_TOKEN
    restart: on-failure
    networks:
      - fancy_weather

  frontend:
    build: "./frontend"
    ports:
      - 8080:80
    networks:
      - fancy_weather

networks:
  fancy_weather:
    driver: bridge
