runcharts:
  - title: Frontend requests
    pty: true
    items:
      - label: total
        sample: docker logs $(docker ps | grep fancy_weather_frontend | awk '{print $1;}') --since 1s | wc -l
      - label: api
        sample: docker logs $(docker ps | grep fancy_weather_frontend | awk '{print $1;}') --since 1s | grep api | wc -l
      - label: errors
        sample: docker logs $(docker ps | grep fancy_weather_frontend | awk '{print $1;}') --since 1s | grep '\[error\]' | wc -l
  - title: Response time
    items:
      - label: api
        sample: curl -o /dev/null -s -w '%{time_total}' http://127.0.0.1:8080/api/v1?message=test
sparklines:
  - title: CPU usage
    sample: ps -A -o %cpu | awk '{s+=$1} END {print s}'
textboxes:
  - title: Docker container stats
    sample: docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemPerc}}\t{{.MemUsage}}\t{{.NetIO}}\t{{.BlockIO}}\t{{.PIDs}}"
