name: tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt

      # Pytest
      - name: Test core
        run: pytest core
      - name: Test pictures
        run: IMGUR_CLIENT=13bfb3e95351a14 pytest pictures
      - name: Tests poems
        run: pytest poems

      # flake8 test
      - name: Run linter
        run: flake8 .

      # Mypy tests
      - name: Check pictures types
        run: mypy -p pictures
      - name: Check poems types
        run: mypy -p poems
      - name: Check core types
        run: mypy -p core
      - name: Check tg_bot types
        run: mypy -p tg_bot
